"""Generate the small, anonymous public floor-plan fixtures using stdlib only."""

from __future__ import annotations

import hashlib
import json
import struct
import zlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "examples" / "fixtures"
WIDTH = 640
HEIGHT = 480


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    body = kind + payload
    return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body))


def _draw_rect(pixels: bytearray, left: int, top: int, right: int, bottom: int, color: tuple[int, int, int]) -> None:
    for y in range(max(0, top), min(HEIGHT, bottom)):
        start = (y * WIDTH + max(0, left)) * 3
        end = (y * WIDTH + min(WIDTH, right)) * 3
        row = bytes(color) * max(0, (end - start) // 3)
        pixels[start:end] = row


def _write_png(path: Path) -> None:
    pixels = bytearray(b"\xff\xff\xff" * WIDTH * HEIGHT)
    wall = (32, 39, 43)
    window = (77, 164, 196)
    door = (176, 116, 62)

    _draw_rect(pixels, 70, 55, 570, 68, wall)
    _draw_rect(pixels, 70, 412, 570, 425, wall)
    _draw_rect(pixels, 70, 55, 83, 425, wall)
    _draw_rect(pixels, 557, 55, 570, 425, wall)
    _draw_rect(pixels, 350, 68, 363, 300, wall)
    _draw_rect(pixels, 350, 360, 363, 412, wall)
    _draw_rect(pixels, 83, 275, 350, 288, wall)
    _draw_rect(pixels, 180, 55, 300, 68, window)
    _draw_rect(pixels, 557, 155, 570, 250, window)
    _draw_rect(pixels, 350, 300, 363, 360, door)

    rows = b"".join(
        b"\x00" + bytes(pixels[y * WIDTH * 3 : (y + 1) * WIDTH * 3])
        for y in range(HEIGHT)
    )
    png = b"\x89PNG\r\n\x1a\n"
    png += _png_chunk(b"IHDR", struct.pack(">IIBBBBB", WIDTH, HEIGHT, 8, 2, 0, 0, 0))
    png += _png_chunk(b"IDAT", zlib.compress(rows, 9))
    png += _png_chunk(b"IEND", b"")
    path.write_bytes(png)


def _write_dxf(path: Path) -> None:
    segments = [
        (0, 0, 500, 0),
        (500, 0, 500, 360),
        (500, 360, 0, 360),
        (0, 360, 0, 0),
        (280, 0, 280, 230),
        (280, 290, 280, 360),
        (0, 220, 280, 220),
    ]
    lines = ["0", "SECTION", "2", "HEADER", "9", "$INSUNITS", "70", "5", "0", "ENDSEC", "0", "SECTION", "2", "ENTITIES"]
    for x1, y1, x2, y2 in segments:
        lines.extend(["0", "LINE", "8", "WALL", "10", str(x1), "20", str(y1), "30", "0", "11", str(x2), "21", str(y2), "31", "0"])
    lines.extend(["0", "ENDSEC", "0", "EOF", ""])
    # DXF is checked in as binary so its generated checksum is identical on every OS.
    path.write_bytes("\n".join(lines).encode("ascii"))


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    png = OUTPUT / "public_floorplan.png"
    dxf = OUTPUT / "public_floorplan.dxf"
    _write_png(png)
    _write_dxf(dxf)
    assets = []
    for path, media_type in ((png, "image/png"), (dxf, "image/vnd.dxf")):
        assets.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "media_type": media_type,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "copyright": "AIPE03 第四組",
                "license": "GPL-3.0-or-later",
                "source": "generated by scripts/generate_public_fixtures.py",
            }
        )
    manifest = {"schema_version": "1.0", "assets": assets}
    (OUTPUT / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
